// @generated by handbook/bin/gen-related-tools.mjs from handbook/tools.json — DO NOT EDIT.
// To change this tool's related-tools section, edit tools.json (this tool's `related[]`, or the
// referenced tools' hub.icon/hub.card), then run `node handbook/bin/gen-related-tools.mjs edit-ascii-diagram`
// (or with no arg to regenerate every active tool) and commit the result.

export interface RelatedToolCard {
  slug: string;
  icon: string;
  name: Record<string, string>;
  desc: Record<string, string>;
}

/** Curated related tools (Issue #177) — same hub.group baseline + genuine cross-group workflow ties. */
export const RELATED_TOOLS: RelatedToolCard[] = [
  {
    "slug": "draw-flowchart",
    "icon": "🖍️",
    "name": {
      "en": "Draw Flowchart",
      "ja": "フローチャート作成",
      "zh": "绘制流程图",
      "de": "Flussdiagramm zeichnen",
      "es": "Dibujar diagrama de flujo"
    },
    "desc": {
      "en": "Write flowchart syntax, see it rendered live. Export as SVG or PNG.",
      "ja": "フローチャート記法を書くとその場でプレビュー。SVG/PNGで書き出し。",
      "zh": "输入流程图语法即时预览，导出为 SVG 或 PNG。",
      "de": "Flussdiagramm-Syntax schreiben und live sehen. Export als SVG oder PNG.",
      "es": "Escribe la sintaxis del diagrama y visualízalo al instante. Exporta como SVG o PNG."
    }
  },
  {
    "slug": "edit-flowchart",
    "icon": "🧩",
    "name": {
      "en": "Edit Flowchart",
      "ja": "フローチャート編集",
      "zh": "编辑流程图",
      "de": "Flussdiagramm bearbeiten",
      "es": "Editar diagrama de flujo"
    },
    "desc": {
      "en": "Edit a Mermaid flowchart visually — structure only, code stays lossless.",
      "ja": "MermaidフローチャートをGUIで構造編集。コードはロスレスに保持。",
      "zh": "以图形界面编辑 Mermaid 流程图结构，代码无损保留。",
      "de": "Bearbeite ein Mermaid-Flussdiagramm visuell — nur Struktur, Code bleibt verlustfrei.",
      "es": "Edita visualmente un diagrama de flujo Mermaid — solo estructura, el código no pierde nada."
    }
  }
];

/** This tool's own engineering-notes article slug (/blog/<slug>/), or null if none is published yet. */
export const BLOG_SLUG: string | null = 'edit-ascii-diagram';
